DROP TABLE IF EXISTS TSCR;

DROP TABLE IF EXISTS TSCRELM;

CREATE TABLE TSCR(
	TSCR_ID INT AUTO_INCREMENT,
	SCR_NAME VARCHAR(256),
	VERSION INT,
	DEL_FLG INT,
	CREATE_USER VARCHAR(128),
	CREATE_DATE DATETIME,
	UPDATE_USER VARCHAR(128),
	UPDATE_DATE TIMESTAMP,
	PRIMARY KEY(TSCR_ID)
);

CREATE TABLE TSCRELM(
	TSCRELM_ID INT AUTO_INCREMENT,
	SERVICE_NAME VARCHAR(256),
	ADAPTER VARCHAR(256),
	PREPARE_INPUT VARCHAR(256),
	TSCR_ID INT,
	ORD_IN_GRP INT,
	VERSION INT,
	DEL_FLG INT,
	CREATE_USER VARCHAR(128),
	CREATE_DATE DATETIME,
	UPDATE_USER VARCHAR(128),
	UPDATE_DATE TIMESTAMP,
	PRIMARY KEY(TSCRELM_ID)
);

CREATE TABLE IF NOT EXISTS TSCRPRM(
	TSCRPRM_ID INT NOT NULL AUTO_INCREMENT,
	PARAM_KEY VARCHAR(256),
	PARAM_VALUE VARCHAR(256),
	TSCR_ID INT,
	ORD_IN_GRP INT,
	VERSION INT,
	DEL_FLG INT,
	CREATE_USER VARCHAR(128),
	CREATE_DATE DATETIME,
	UPDATE_USER VARCHAR(128),
	UPDATE_DATE TIMESTAMP,
	PRIMARY KEY(TSCRPRM_ID)
);

INSERT INTO TSCR(TSCR_ID, SCR_NAME, VERSION, DEL_FLG, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (1000002, 'DB構成更新', 1, 0, 'data_loader', '2023-09-09 00:00:00', 'data_loader', '2023-09-09 00:00:00');

INSERT INTO TSCRELM (TSCRELM_ID, SERVICE_NAME, ADAPTER, PREPARE_INPUT, TSCR_ID, ORD_IN_GRP, VERSION, DEL_FLG, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (1000011, 'com.jc.service.dbmng.common.UpdateSqlByDefService', '', '', 1000002, 1, 1, 0, 'data_loader', '2023-09-09 00:00:00', 'data_loader', '2023-09-09 00:00:00');
INSERT INTO TSCRELM (TSCRELM_ID, SERVICE_NAME, ADAPTER, PREPARE_INPUT, TSCR_ID, ORD_IN_GRP, VERSION, DEL_FLG, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (1000012, 'com.jc.service.dbmng.common.UpdateSqlByDataService', '', '', 1000002, 2, 1, 0, 'data_loader', '2023-09-09 00:00:00', 'data_loader', '2023-09-09 00:00:00');
INSERT INTO TSCRELM (TSCRELM_ID, SERVICE_NAME, ADAPTER, PREPARE_INPUT, TSCR_ID, ORD_IN_GRP, VERSION, DEL_FLG, CREATE_USER, CREATE_DATE, UPDATE_USER, UPDATE_DATE) VALUES (1000013, 'com.jc.service.dbmng.common.UpdateAllTableService', '', '', 1000002, 3, 1, 0, 'data_loader', '2023-09-09 00:00:00', 'data_loader', '2023-09-09 00:00:00');
