DROP TABLE IF EXISTS TBLDEF;

CREATE TABLE TBLDEF(
	TBLDEF_ID INT NOT NULL AUTO_INCREMENT(1),
	TABLE_NAME VARCHAR(256),
	FIELD_NAME VARCHAR(256),
	TYPE_NAME VARCHAR(256),
	ALLOW_NULL VARCHAR(256),
	KEY_DIV VARCHAR(256),
	DEFAULT_VALUE VARCHAR(256),
	EXTRA VARCHAR(256),
	PRIMARY KEY(TBLDEF_ID)
);

INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'TSCR_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'SCR_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');
