DROP TABLE IF EXISTS MTBLDEF;

CREATE TABLE MTBLDEF(
	MTBLDEF_ID INT NOT NULL AUTO_INCREMENT(1),
	TABLE_NAME VARCHAR(256),
	FIELD_NAME VARCHAR(256),
	TYPE_NAME VARCHAR(256),
	ALLOW_NULL VARCHAR(256),
	KEY_DIV VARCHAR(256),
	DEFAULT_VALUE VARCHAR(256),
	EXTRA VARCHAR(256),
	PRIMARY KEY(MTBLDEF_ID)
);

INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'TSCR_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'SCR_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'DEL_FLG', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'CREATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'CREATE_DATE', 'DATETIME', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'UPDATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'UPDATE_DATE', 'TIMESTAMP', 'YES', '', null, '');
