DROP TABLE IF EXISTS MTBLDEF;

CREATE TABLE MTBLDEF(
	MTBLDEF_ID INT NOT NULL AUTO_INCREMENT(1),
	TABLE_NAME VARCHAR(256),
	FIELD_NAME VARCHAR(256),
	TYPE_NAME VARCHAR(256),
	ALLOW_NULL VARCHAR(256),
	KEY_DIV VARCHAR(256),
	DEFAULT_VALUE VARCHAR(256),
	EXTRA VARCHAR(256),
	PRIMARY KEY(MTBLDEF_ID)
);

INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'MGNRGRP_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'GNR_GRP_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'DEL_FLG', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'CREATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'CREATE_DATE', 'DATETIME', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'UPDATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'UPDATE_DATE', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'MGNRKEYVAL_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'GNR_KEY', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'GNR_VAL', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'MGNRGRP_ID', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'ORD_IN_GRP', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'DEL_FLG', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'CREATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'CREATE_DATE', 'DATETIME', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'UPDATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'UPDATE_DATE', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO MTBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('MTBLDEF', 'MTBLDEF_ID', 'INT', 'NO', 'PRI', NULL, 'AUTO_INCREMENT');
INSERT INTO MTBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('MTBLDEF', 'TABLE_NAME', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO MTBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('MTBLDEF', 'FIELD_NAME', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO MTBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('MTBLDEF', 'TYPE_NAME', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO MTBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('MTBLDEF', 'ALLOW_NULL', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO MTBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('MTBLDEF', 'KEY_DIV', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO MTBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('MTBLDEF', 'DEFAULT_VALUE', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO MTBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('MTBLDEF', 'EXTRA', 'VARCHAR(256)', 'YES', '', NULL, '');

INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'TACCOUNT_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'ACCOUNT_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'PASSWORD', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'DEL_FLG', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'CREATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'CREATE_DATE', 'DATETIME', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'UPDATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'UPDATE_DATE', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'TMAIL_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'MAIL_FROM', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'MAIL_SUBJECT', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'SENT_DATE', 'DATETIME', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'HONBUN', 'VARCHAR(8192)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'DEL_FLG', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'CREATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'CREATE_DATE', 'DATETIME', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'UPDATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'UPDATE_DATE', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'TSCR_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'SCR_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'DEL_FLG', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'CREATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'CREATE_DATE', 'DATETIME', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'UPDATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'UPDATE_DATE', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'TSCRELM_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'SERVICE_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'ADAPTER', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'PREPARE_INPUT', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'TSCR_ID', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'ORD_IN_GRP', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'DEL_FLG', 'INT', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'CREATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'CREATE_DATE', 'DATETIME', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'UPDATE_USER', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO MTBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'UPDATE_DATE', 'TIMESTAMP', 'YES', '', null, '');
