DROP TABLE IF EXISTS TBLDEF;

CREATE TABLE TBLDEF(
	TBLDEF_ID INT NOT NULL AUTO_INCREMENT(1),
	TABLE_NAME VARCHAR(256),
	FIELD_NAME VARCHAR(256),
	TYPE_NAME VARCHAR(256),
	ALLOW_NULL VARCHAR(256),
	KEY_DIV VARCHAR(256),
	DEFAULT_VALUE VARCHAR(256),
	EXTRA VARCHAR(256),
	PRIMARY KEY(TBLDEF_ID)
);

INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'MGNRGRP_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'GNR_GRP_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRGRP', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'MGNRKEYVAL_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'GNR_KEY', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'GNR_VAL', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'MGNRGRP_ID', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'ORD_IN_GRP', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('MGNRKEYVAL', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO TBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBLDEF', 'TBLDEF_ID', 'INT', 'NO', 'PRI', NULL, 'AUTO_INCREMENT');
INSERT INTO TBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBLDEF', 'TABLE_NAME', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBLDEF', 'FIELD_NAME', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBLDEF', 'TYPE_NAME', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBLDEF', 'ALLOW_NULL', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBLDEF', 'KEY_DIV', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBLDEF', 'DEFAULT_VALUE', 'VARCHAR(256)', 'YES', '', NULL, '');
INSERT INTO TBLDEF (TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES ('TBLDEF', 'EXTRA', 'VARCHAR(256)', 'YES', '', NULL, '');

INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'TACCOUNT_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'ACCOUNT_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'PASSWORD', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TACCOUNT', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'TMAIL_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'MAIL_FROM', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'MAIL_SUBJECT', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'SENT_DATE', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'HONBUN', 'VARCHAR(8192)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TMAIL', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'TSCR_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'SCR_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCR', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');

INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'TSCRELM_ID', 'INT', 'NO', 'PRI', null, 'AUTO_INCREMENT');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'SERVICE_NAME', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'ADAPTER', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'PREPARE_INPUT', 'VARCHAR(256)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'TSCR_ID', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'ORD_IN_GRP', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'VERSION', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'IS_DELETED', 'INT', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'CREATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'CREATED_AT', 'DATETIME', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'UPDATED_BY', 'VARCHAR(128)', 'YES', '', null, '');
INSERT INTO TBLDEF(TABLE_NAME, FIELD_NAME, TYPE_NAME, ALLOW_NULL, KEY_DIV, DEFAULT_VALUE, EXTRA) VALUES('TSCRELM', 'UPDATED_AT', 'TIMESTAMP', 'YES', '', null, '');
